FROM openjdk:8-jre

MAINTAINER corn

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JAVA_OPTS="" \
    PORT=8002 \
    PROFILES="default"
WORKDIR /opt/
#ADD /target/*.jar /gateway.jar
ADD ./*v1.jar /istio-b-service.jar

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /istio-b-service.jar --spring.profiles.active=$PROFILES"]

EXPOSE $PORT
####docker build -f Dockerfile-v1 -t corn/istio-b-service-v1:1.0.0 .
