apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-service
  namespace: msistio
  labels:
    app: a-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: a-service
  template:
    metadata:
      labels:
        app: a-service
    spec:
      serviceAccountName: msistio-admin
      containers:
        - name: a-service
          image: corn/istio-a-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          ##指定镜像挂在文件的路径
          volumeMounts:
            - name: a-svc-config
              ##镜像运行制定配置文件的路径要一致:/config/myconfig.yml
              mountPath: config
      volumes:
        - name: a-svc-config
          configMap:
            name: a-service
            items:
              - key: myconfig.yml
                path: myconfig.yml
      restartPolicy: Always
