apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: msistio
  labels:
    app: auth-service
    service: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8080
      name: tomcat