apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: msistio
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: msistio-admin
      containers:
        - name: auth-service
          image: corn/istio-auth-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
