apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-service-v1
  namespace: msistio
  labels:
    app: b-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b-service
      version: v1
  template:
    metadata:
      labels:
        app: b-service
        version: v1
    spec:
      serviceAccountName: msistio-admin
      containers:
        - name: a-service
          image: corn/istio-b-service-v1:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
