apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-service
  namespace: msistio
  labels:
    app: b-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: b-service
  template:
    metadata:
      labels:
        app: b-service
    spec:
      serviceAccountName: msistio-admin
      containers:
        - name: a-service
          image: corn/istio-b-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
