apiVersion: v1
kind: Service
metadata:
  name: b-service
  namespace: msistio
  labels:
    app: b-service
    service: b-service
spec:
  selector:
    app: b-service
  ports:
    - port: 8080
      name: tomcat