apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: msistio-admin-role-binding
  namespace: msistio
roleRef:
  kind: Role
  name: msistio-admin-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: msistio-admin
    namespace: msistio
